global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'smart-billing-app'
    metrics_path: '/metrics' 
    static_configs:
      - targets: ['smart-billing-app:8000']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
