"""Change government_id to Integer

Revision ID: 2e749c2962ee
Revises: 5e380b0389a3
Create Date: 2024-11-29 15:05:31.871341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e749c2962ee'
down_revision: Union[str, None] = '5e380b0389a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 
        'government_id',
        type_=sa.Integer,
        postgresql_using='government_id::integer'  # Adiciona a conversão explícita
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 
        'government_id',
        type_=sa.String,
        postgresql_using='government_id::text'  # Reverter para texto
    )
    # ### end Alembic commands ###
