"""Add server_default for created_at fields

Revision ID: 5e380b0389a3
Revises: dfd9c60a0739
Create Date: 2024-11-29 14:07:48.426161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e380b0389a3'
down_revision: Union[str, None] = 'dfd9c60a0739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debts', 'created_at', server_default=sa.func.now(), existing_type=sa.TIMESTAMP())
    op.alter_column('users', 'created_at', server_default=sa.func.now(), existing_type=sa.TIMESTAMP())
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
